version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dult-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1oxqkawri67d5"
s3_prefix = "dult-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
